{
  imports = [
    ./base.nix
    ./desktop.nix
    ./dev.nix
    ./edf-sf.nix
    ./gaming.nix
    ./git.nix
    ./gnome.nix
    ./home.nix
    ./i18n.nix
    ./i3.nix
    ./ipfs.nix
    ./keybase.nix
    ./laptop.nix
    ./mail.nix
    ./nix-auto-update.nix
    ./printing.nix
    ./qemu.nix
    ./scanning.nix
    ./sway.nix
    ./zsh.nix
  ];
}
