# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  sources = import ../../nix/sources.nix;
in
{
  imports = [
    (sources.nixos-hardware + "/dell/xps/13-9310")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelPackages = lib.mkIf (lib.versionOlder pkgs.linux.version "5.6") pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/141245d9-0df4-4627-bd29-e6a941150033";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/0695-EB46";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/13f5f86e-b62d-4fa8-a945-9fc4682eb020"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
